
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/providers'
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ['latin'] })
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Catálago Beauty',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>

      <body className={inter.className}>   
      <Providers>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        {children}</Providers></body>
    </html>
  )
}
